apiVersion: drone.polito.com/v1alpha1
kind: DroneFederatedDeployment
metadata:
  name: nginx-dronefederateddeployment
spec:
  schedule: "2019-10-28T10:12:00Z"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:latest
              resources:
                limits:
                  cpu: "1"
                  memory: "512"
  placement:
    clusters:
      - name: cluster2

#spec:
#  schedule: "2019-04-12T10:12:00Z"
#  app-name: "VLC-1080"
#  base-node: "cluster1"
#  type: "ADD"
#  components:
#    - name: "gui"
#      function:
#        image: "andreamora/vlc:latest"
#        resources:
#          memory: 512
#          cpu: 0.6
#      parameters:
#        ip: ""
#        service-name: "service-streamer"
#        name-to-deploy: "gui-component"
#      boot_dependencies:
#      nodes-blacklist:
#      nodes-whitelist:
#        - name: "cluster1"
#    - name: "streamer"
#      function:
#        image: "andreamora/vlc:latest"
#        resources:
#          memory: 1024
#          cpu: 0.5
#        parameters:
#          path: "/home/vlc/videoBigBunny1080.mp4"
#          quality: "high"
#          service: "true"
#          service-name: "service-streamer"
#          name-to-deploy: "streamer-component"
#        boot_dependencies:
#        nodes-blacklist:
#        nodes-whitelist: