apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dronefederateddeployments.drone.polito.com
spec:
  group: drone.polito.com
  names:
    kind: DroneFederatedDeployment
    listKind: DroneFederatedDeploymentList
    plural: dronefederateddeployments
    singular: dronefederateddeployment
    shortNames:
    - dfd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns: #(optional)
    - name: schedule
      type: string
      JSONPath: .spec.schedule
    - name: creation
      type: string
      JSONPath: .metadata.creationTimestamp
    - name: phase
      type: string
      JSONPath: .status.phase