apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-operator
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drone-operator
  template:
    metadata:
      labels:
        name: drone-operator
    spec:
      serviceAccountName: drone-operator
      containers:
        - name: drone-operator
          # Replace this with the built image name
          image: drone-operator:first
          command:
          - drone-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "drone-operator"
